version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/dat
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=postgres
      -  POSTGRES_HOST=db

    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      sh -c "alembic upgrade head &&
             python run_game.py"
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq  

volumes:
  pgdata:
