"""add column to player model

Revision ID: 190107501c23
Revises: ab955f99a8f6
Create Date: 2023-09-23 19:54:31.789172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190107501c23'
down_revision = 'ab955f99a8f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
