"""company model fix

Revision ID: 26464ee61a70
Revises: 4e15c70a39c6
Create Date: 2023-09-27 04:42:05.552480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26464ee61a70'
down_revision = '4e15c70a39c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingamecompanys_title_key', 'ingamecompanys', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingamecompanys_title_key', 'ingamecompanys', ['title'])
    # ### end Alembic commands ###
