"""altered tables

Revision ID: 48dcc763fa29
Revises: 6be29841a80e
Create Date: 2023-09-25 19:32:07.277501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dcc763fa29'
down_revision = '6be29841a80e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
