"""fixed game model

Revision ID: 4e15c70a39c6
Revises: 6f8142895165
Create Date: 2023-09-27 02:35:32.416809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e15c70a39c6'
down_revision = '6f8142895165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
