"""initial 3

Revision ID: 5a3a492498d8
Revises: 31a6f0905ef5
Create Date: 2023-09-22 18:38:04.501452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3a492498d8'
down_revision = '31a6f0905ef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
