"""fix players

Revision ID: 6084f037749a
Revises: bc2923e33665
Create Date: 2023-09-29 19:32:51.441380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6084f037749a'
down_revision = 'bc2923e33665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_vk_id_key', 'players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('players_vk_id_key', 'players', ['vk_id'])
    # ### end Alembic commands ###
