"""altered tables

Revision ID: 6be29841a80e
Revises: 97f03adbde39
Create Date: 2023-09-25 19:23:23.855307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be29841a80e'
down_revision = '97f03adbde39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.add_column('players', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'game_id')
    op.create_table('scores',
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capital', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clear_capital', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='scores_game_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='scores_player_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id', name='scores_pkey')
    )
    # ### end Alembic commands ###
