"""altered stock model

Revision ID: 6f8142895165
Revises: 7d7f2aedf8cc
Create Date: 2023-09-27 00:34:46.149910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8142895165'
down_revision = '7d7f2aedf8cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('max_rounds', sa.Integer(), nullable=False))
    op.drop_column('stocks', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('games', 'max_rounds')
    # ### end Alembic commands ###
