"""initial 3

Revision ID: 7ae683de0ac5
Revises: a2883045d380
Create Date: 2023-09-22 18:34:26.573124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae683de0ac5'
down_revision = 'a2883045d380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
