"""alter player model

Revision ID: 7d7f2aedf8cc
Revises: 48dcc763fa29
Create Date: 2023-09-25 19:48:27.339837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7f2aedf8cc'
down_revision = '48dcc763fa29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('capital', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('clear_capital', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'clear_capital')
    op.drop_column('players', 'capital')
    # ### end Alembic commands ###
