"""alter player model

Revision ID: 8c1fd80f1468
Revises: 190107501c23
Create Date: 2023-09-23 19:55:54.373288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1fd80f1468'
down_revision = '190107501c23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'name')
    # ### end Alembic commands ###
