"""alter gamemodel, added ingamecompany model

Revision ID: 97f03adbde39
Revises: 8c1fd80f1468
Create Date: 2023-09-24 21:19:03.848388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f03adbde39'
down_revision = '8c1fd80f1468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingamecompanys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('current_stock_price', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('games', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('games', sa.Column('current_round', sa.Integer(), nullable=True))
    op.drop_constraint('stocks_company_id_fkey', 'stocks', type_='foreignkey')
    op.create_foreign_key(None, 'stocks', 'ingamecompanys', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.create_foreign_key('stocks_company_id_fkey', 'stocks', 'companys', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('games', 'current_round')
    op.drop_column('games', 'is_active')
    op.drop_table('ingamecompanys')
    # ### end Alembic commands ###
