"""added stocks to gamemodel

Revision ID: ad9a2e9386c9
Revises: 26464ee61a70
Create Date: 2023-09-28 01:10:02.730430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9a2e9386c9'
down_revision = '26464ee61a70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocks', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'game_id')
    # ### end Alembic commands ###
