"""Deleted comp model

Revision ID: bc2923e33665
Revises: ad9a2e9386c9
Create Date: 2023-09-29 01:12:55.675208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2923e33665'
down_revision = 'ad9a2e9386c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_stock_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='companys_pkey'),
    sa.UniqueConstraint('title', name='companys_title_key')
    )
    # ### end Alembic commands ###
