"""on delete in company model

Revision ID: c80f4a77eea9
Revises: 6084f037749a
Create Date: 2023-09-30 22:45:49.779861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80f4a77eea9'
down_revision = '6084f037749a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingamecompanys_game_id_fkey', 'ingamecompanys', type_='foreignkey')
    op.create_foreign_key(None, 'ingamecompanys', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingamecompanys', type_='foreignkey')
    op.create_foreign_key('ingamecompanys_game_id_fkey', 'ingamecompanys', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
